postsCounter/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from .views import custom_404_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path("posts/", include("posts.urls")),
]

handler404 = custom_404_view

postsCounter/posts/urls.py
from django.urls import path
from .views import add_news, register, login_view, logout_view, popular_topics

urlpatterns = [
    path('', popular_topics, name='popular_topics'),
    path('add/', add_news, name='add_news'),
    
    path('register/', register, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout',),
]

postsCounter/posts/models.py
from django.db import models
from django.contrib.auth.models import User

class News(models.Model):
    title = models.CharField(max_length=256)
    popularity = models.IntegerField(default=1)
    added_by = models.ManyToManyField(User)

    def __str__(self):
        return self.title

postsCounter/posts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import News

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2')

class NewsForm(forms.ModelForm):
    title = forms.CharField(max_length=255)

    class Meta:
        model = News
        fields = ['title']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
    
    def clean_title(self):
        title = self.cleaned_data['title']
        news = News.objects.filter(title=title).first()

        
        if not news:
            return title

        if news.added_by.filter(id=self.user.id).exists():
            raise forms.ValidationError('Вы уже добавили эту тему')
        
        return title

    def save(self, commit=True):
        title = self.cleaned_data['title']
        try:
            news = News.objects.get(title=title)
            news.added_by.add(self.user)
            news.popularity += 1
            news.save()
        except News.DoesNotExist:
            news = super().save(commit=False)
            news.save()
            news.added_by.add(self.user)
        return news

postsCounter/main/views.py
from django.shortcuts import redirect

def custom_404_view(request, exception):
    return redirect('/') 

postsCounter/posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from .forms import SignUpForm, NewsForm
from .models import News
from django.core.paginator import Paginator
from django.db.models import Sum 
from django.contrib.auth.models import User

def register(request):
    if request.user.is_authenticated:
        return redirect('/posts/') 
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/posts/')
    else:
        form = SignUpForm()
    return render(request, 'registration/register.html', {'form': form})

def login_view(request):
    if request.user.is_authenticated:
        return redirect('/posts/') 
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/posts/')
    else:
        form = AuthenticationForm()
    return render(request, 'registration/login.html', {'form': form, 'hidden_login_button': True})

@login_required
def logout_view(request):
    logout(request)
    return redirect('/posts/')

def add_news(request):
    if not request.user.is_authenticated:
        return redirect('/posts/login/') 
    if request.method == 'POST':
        form = NewsForm(request.POST, user=request.user)
        if form.is_valid():
            form.save()
            return redirect('popular_topics')
    else:
        form = NewsForm()
    return render(request, 'add_news.html', {'form': form})

def popular_topics(request):
    popular_news = News.objects.order_by('-popularity')
    paginator = Paginator(popular_news, 5) 
    page_number = request.GET.get('page') 
    page_obj = paginator.get_page(page_number) 

    for news in page_obj:
        added_by_ids = news.added_by.values_list('id', flat=True)
        added_by_users = User.objects.filter(id__in=added_by_ids)
        news.added_by_users = added_by_users

    popular_topics = News.objects.values('title').annotate(total_popularity=Sum('popularity')).order_by('-total_popularity')[:3]

    for topic in popular_topics:
        topic['popularity'] = News.objects.filter(title=topic['title']).aggregate(total_popularity=Sum('popularity'))['total_popularity']
        added_by_ids = News.objects.filter(title=topic['title']).first().added_by.values_list('id', flat=True)
        added_by_users = User.objects.filter(id__in=added_by_ids)
        topic['added_by'] = [{'first_name': user.first_name, 'last_name': user.last_name, 'username': user.username} for user in added_by_users]

    return render(request, 'popular_topics.html', {'page_obj': page_obj, 'popular_topics': popular_topics})

postsCounter/posts/templates/add_news.html
{% extends "base.html" %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'styles/add_news.css' %}?v=1.0.1" />
{% endblock head %}

{% block content %}
  <div class="add-news">
    <h1>Добавление заголовка</h1>

    <form method="post">
      {% csrf_token %}
      <label for="id_title">Введите заголовок</label>

      <textarea type="text" id="id_title" name="title" required></textarea>

      {% if form.errors %}
        <ul>
          {% for field, errors in form.errors.items %}
            {% for error in errors %}
              <li>{{ error }}</li>
            {% endfor %}
          {% endfor %}
        </ul>
      {% endif %}

      <button type="submit">Добавить</button>
    </form>
  </div>
{% endblock content %}

postsCounter/posts/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8" />

    <title>{% block title %}Популярные новости - NEWSCOUNTER{% endblock title %}</title>

    <link rel="icon" type="image/x-icon" href="{% static 'images/logo.svg' %}">

    <link rel="stylesheet" href="{% static 'styles/reset.css' %}?v=1.0.1" />
    <link rel="stylesheet" href="{% static 'styles/header.css' %}?v=1.0.2" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">

    {% block head %}{% endblock head %}
  </head>
  <body>
    <header class="header">
      <div class="header__box">
        <a href="/posts/" class="header__logo">
          <svg xmlns="http://www.w3.org/2000/svg" width="800px" height="800px" viewBox="0 0 24 24" fill="none">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M2 5C2 3.34315 3.34315 2 5 2H19C20.6569 2 22 3.34315 22 5V19C22 20.6569 20.6569 22 19 22H5C3.34315 22 2 20.6569 2 19V5ZM5 4C4.44772 4 4 4.44772 4 5V10H20V5C20 4.44772 19.5523 4 19 4H5ZM4 12V19C4 19.5523 4.44772 20 5 20H19C19.5523 20 20 19.5523 20 19V12H4ZM14 13C14.2652 13 14.5196 13.1054 14.7071 13.2929L18.7071 17.2929C19.0976 17.6834 19.0976 18.3166 18.7071 18.7071C18.3166 19.0976 17.6834 19.0976 17.2929 18.7071L14 15.4142L11.7071 17.7071L10.7071 18.7071C10.3166 19.0976 9.68342 19.0976 9.29289 18.7071C8.90237 18.3166 8.90237 17.6834 9.29289 17.2929L9.58579 17L9 16.4142L6.70711 18.7071C6.31658 19.0976 5.68342 19.0976 5.29289 18.7071C4.90237 18.3166 4.90237 17.6834 5.29289 17.2929L8.29289 14.2929C8.48043 14.1054 8.73478 14 9 14C9.26522 14 9.51957 14.1054 9.70711 14.2929L11 15.5858L13.2929 13.2929C13.4804 13.1054 13.7348 13 14 13ZM11 7C11 6.44772 11.4477 6 12 6H17C17.5523 6 18 6.44772 18 7C18 7.55228 17.5523 8 17 8H12C11.4477 8 11 7.55228 11 7ZM7 8.75C7.9665 8.75 8.75 7.9665 8.75 7C8.75 6.0335 7.9665 5.25 7 5.25C6.0335 5.25 5.25 6.0335 5.25 7C5.25 7.9665 6.0335 8.75 7 8.75Z" fill="#0047ff"/>
          </svg>
          NEWSCOUNTER
          <span>.com</span>
        </a>
      </div>

      {% if user.is_authenticated %}
        <nav class="header__nav">
          {% if user.is_authenticated %}
            <a href="/posts/add" class="header__link">
              Добавить заголовок
            </a>
          {% endif %}

          <p class="header__user-info">
            <span>{{ user.first_name }} {{ user.last_name }} - </span> @{{ user.username }}
          </p>

          <a href="/posts/logout" class="header__auth-btn">
            Выйти
          </a>
        </nav>
      {% else %}
        {% if not hidden_login_button %}
          <a href="/posts/login" class="header__auth-btn">
            Авторизация
          </a>
        {% else %}
          <a href="/posts/register" class="header__auth-btn">
            Регистрация
          </a>
        {% endif %}
      {% endif %}
    </header>

    {% block content %}{% endblock content %}
    {% block scripts %}{% endblock scripts %}
  </body>
</html>

postsCounter/posts/templates/popular_topics.html
{% extends "base.html" %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'styles/posts.css' %}?v=1.0.5" />
  <link rel="stylesheet" href="{% static 'styles/pagination.css' %}?v=1.0.0" />
{% endblock head %}

{% block content %}
  <div class="posts">
    <div class="posts-all">
      <h1>Заголовки новостей</h1>
      <div class="posts-all__list">
        {% for news in page_obj %}
          <div class="list">
            <div class="list__box">
              <p>{{ news.title }}</p>
              <div class="list__box-users">
                {% for user in news.added_by_users %}
                  <div>{{ user.first_name }} {{ user.last_name }} - <span>@{{ user.username }}</span></div>
                {% endfor %}
              </div>
            </div>

            <p>Популярность: {{ news.popularity }}</p>
          </div>
        {% endfor %}
      </div>

      <div class="pagination">
        {% if page_obj.has_previous %}
          <a href="?page={{ page_obj.previous_page_number }}" class="pagination__btn">Пред.</a>
        {% else %}
          <div class="pagination__btn pagination__btn-disabled">Пред.</div>
        {% endif %}

        <span>{{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>

        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}" class="pagination__btn">След.</a>
        {% else %}
          <div class="pagination__btn pagination__btn-disabled">След.</div>
        {% endif %}
      </div>
    </div>

    <div class="posts-fire">
      <h1>Горячие заголовки</h1>
      <div class="posts-fire__list">
        {% for topic in popular_topics %}
          <div class="list">
            <div class="list__box">
              <p>{{ topic.title }}</p>
              <div class="list__box-users">
                {% for user in topic.added_by %}
                  <div>{{ user.first_name }} {{ user.last_name }} - <span>@{{ user.username }}</span></div>
                {% endfor %}
              </div>
            </div>

            <p>Популярность: {{ topic.popularity }}</p>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock content %}